### ISSUE TITLE
Release amichair PR

### ISSUE THREAD

**Issue by skjolber** [skjolber/mockito-soap-cxf#16]
@amichair I've merged your pull-requests, very good work! If you're happy / finished, I'll release it later today. :+1: :+1:

**Comment by skjolber** [comment]
Release 1.0.5 i out with your improvements. :1st_place_medal:

**Comment by amichair** [comment]
Thanks for the very quick merges and release! Your responsiveness is very much appreciated :-)

Made one more PR with some leftover refactoring/cleanup for the next release. Also opened an issue for the exception seen on Travis test failure, not entirely sure how to deal with it, perhaps someone with more experience with CXF internals will see the solution more easily.
