### ISSUE TITLE
Support to mock soap faults for different HTTP Status Code

### ISSUE THREAD

**Issue by writemevenkat** [skjolber/mockito-soap-cxf#2]
Hi Thomas, This really helped me a lot to mock the services for unit testing in spring boot/camel, I'm trying to throw a soap fault response with different HTTP status codes and it only works for HTTP 500. When i tired with 401 or 402, I got the following error "org.apache.cxf.interceptor.Fault: Could not send Message" instead of getting the soap fault response. see if you can help here ?

**Comment by skjolber** [comment]
Do you have a representative example?
