### ISSUE TITLE
Ability to mock out an invalid (non-xml) return from endpoint?

### ISSUE THREAD

**Issue by chrisrohr** [skjolber/mockito-soap-cxf#23]
Hi, I'm really glad I found this utility as it helps simplify my testing.  I have a use case that is probably very much an edge case and I wish I didn't even have to deal with it, but occasionally I have to deal with the fact that the endpoint I'm using is returning a text/html response instead of xml.  (This is a known bug on my provider, but since I don't control it I have to handle it).  The result ends up in an UnsupportedMediaException instead of a SOAP fault.  I was really just wondering if this is possible with this library or not.

Thank you

**Comment by skjolber** [comment]
Hi @chrisrohr sorry for the delay, this passed under the radar. 

I guess a simple approach would be stopping the mock soap endpoint in the middle of the unit test, and then have another mock tool take the port and return alternative data. 

Getting under the hood of the SOAP HTTP-server might be possible too, but I have not tried it.

**Comment by chrisrohr** [comment]
Thank you for the response
