### ISSUE TITLE
Improvement: would like to be able to use local:// transport

### ISSUE THREAD

**Issue by aukevanleeuwen** [skjolber/mockito-soap-cxf#7]
Hey! Thanks for your library, something I had in mind to create but a quick google search returned me this :-)

Anyway, I'd like to use this library in combination with using the `local://` transport, but there is [some code](https://github.com/skjolber/mockito-soap-cxf/blob/841dc8e8a0ac6288707ee051d38a8b057cb1a01f/src/main/java/com/skjolberg/mockito/soap/SoapServerRule.java#L40-L44) which validates the URL in the `SoapServerRule` which prevents that from working. 

```java
		try {
			new URL(address);
		} catch (MalformedURLException e) {
			throw new IllegalArgumentException("Expected valid address: " + address, e);
		}
```

I'd thought it would be easy enough to fix, (and it is), but I had some problems with the test suite because apparently deep down in CXF there is still some shared state in a `ThreadLocal` that was causing some issues when switching between transports in the tests.

I have a PR upcoming, so you can have a look. This issue is more or less if people are searching for similar issues.

**Comment by skjolber** [comment]
@aukevanleeuwen thanks for the PR (with the unit tests!). I've released version 1.0.4.
